<?php

/**
 * @file
 * Contains drupal_angular.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function seggroup_service_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the drupal_angular module.
    case 'help.page.seggroup_service':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module to manage seggroup services') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function seggroup_service_theme() {
  return [
    'seggroup_service' => [
      'render element' => 'children',
    ],
  ];
}

