<?php

/**
 * @file
 * Contains contact.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function contact_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the contact module.
    case 'help.page.contact':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module to manage form contact and send mail') . '</p>';
      return $output;
    
    default:
  }
}

/**
 * Implements hook_theme().
 */
function contact_theme($existing, $type, $theme, $path) {
  return [
    'contact_theme1' => array(
      'variables' => array(
        'uuid' => NULL,
        'form' => NULL,
        'config' => NULL,
      ),
      'template' => 'block--contact-form',
      'render element' => 'form',
    ),
  ];
}

/**
 * Implements hook_mail
 * @param $key
 * @param $message
 * @param $params
 */
function contact_mail($key, &$message, $params) {
  $data['user'] = $params['account'];
  $options['langcode'] = $message['langcode'];
  //user_mail_tokens($variables, $data, $options);
  switch($key) {
    case 'test':
      //$message['from'] = \Drupal::config('system.site')->get('mail');
      $message['from'] = 'somosgruposeg@gmail.com';
      $message['subject'] = t('Notificación: @email', array('@email' => $params['email']), $options);
      //$message['body'][] = $params['message'];
      $message['body'][] = t(
        'mi nombre es: @name 
        mi telefono es: @phone_number 
        mi correo es: @email 
        mi solicitud es: @description',
        array(
          '@name' => $params['name'],
          '@email' => $params['email'],
          '@phone_number' => $params['phone_number'],
          '@description' => $params['description']
        ));
      break;
  }
}